-- MySQL Script generated by MySQL Workbench
-- Wed Mar 20 10:01:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `sigla` VARCHAR(4) NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `inscMunicipal` VARCHAR(15) NULL,
  `inscEstadual` VARCHAR(45) NULL,
  `endereco` VARCHAR(145) NULL,
  `site` VARCHAR(45) NULL,
  `info` TEXT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcao` (
  `idFuncao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cbo` VARCHAR(7) NULL,
  `obs` VARCHAR(245) NULL,
  PRIMARY KEY (`idFuncao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ContatoExt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ContatoExt` (
  `idContato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(12) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Funcao_idFuncao` INT NOT NULL,
  PRIMARY KEY (`idContato`),
  INDEX `fk_Contato_Cliente_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Contato_Funcao1_idx` (`Funcao_idFuncao` ASC),
  CONSTRAINT `fk_Contato_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contato_Funcao1`
    FOREIGN KEY (`Funcao_idFuncao`)
    REFERENCES `mydb`.`Funcao` (`idFuncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*
-- -----------------------------------------------------
-- Table `mydb`.`Contato_has_Funcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contato_has_Funcao` (
  `Contato_idContato` INT NOT NULL,
  `Contato_Cliente_idCliente` INT NOT NULL,
  `Funcao_idFuncao` INT NOT NULL,
  PRIMARY KEY (`Contato_idContato`, `Contato_Cliente_idCliente`, `Funcao_idFuncao`),
  INDEX `fk_Contato_has_Funcao_Funcao1_idx` (`Funcao_idFuncao` ASC),
  INDEX `fk_Contato_has_Funcao_Contato1_idx` (`Contato_idContato` ASC, `Contato_Cliente_idCliente` ASC),
  CONSTRAINT `fk_Contato_has_Funcao_Contato1`
    FOREIGN KEY (`Contato_idContato` , `Contato_Cliente_idCliente`)
    REFERENCES `mydb`.`ContatoExt` (`idContato` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contato_has_Funcao_Funcao1`
    FOREIGN KEY (`Funcao_idFuncao`)
    REFERENCES `mydb`.`Funcao` (`idFuncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
*/

-- -----------------------------------------------------
-- Table `mydb`.`Certificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Certificacao` (
  `idCertificacao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `desc` VARCHAR(45) NULL,
  `ano` DATE NULL,
  `revisao` VARCHAR(10) NULL,
  PRIMARY KEY (`idCertificacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `validadeCertificacao` DATE NULL,
  `dtAvaliacao` DATE NULL,
  `validadeServico` DATE NULL,
  `Certificacao_idCertificacao` INT NOT NULL,
  PRIMARY KEY (`idFornecedor`),
  INDEX `fk_Fornecedor_Certificacao1_idx` (`Certificacao_idCertificacao` ASC),
  CONSTRAINT `fk_Fornecedor_Certificacao1`
    FOREIGN KEY (`Certificacao_idCertificacao`)
    REFERENCES `mydb`.`Certificacao` (`idCertificacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `obs` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servico` (
  `idServico` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(150) NULL,
  `prazoEntrega` INT NULL,
  PRIMARY KEY (`idServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Identificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Identificacao` (
  `idIdentificacao` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(14) NOT NULL,
  `nisPisPasepInss` VARCHAR(45) NULL,
  `ctps` VARCHAR(7) NULL,
  `serie` VARCHAR(5) NULL,
  `dtExpedicaoCtps` DATE NULL,
  `rg` VARCHAR(12) NOT NULL,
  `dtExpedicaoRg` DATE NULL,
  `cnh` VARCHAR(11) NULL,
  `categoriaCnh` CHAR(2) NULL,
  `dtValidade` DATE NULL,
  `tituloEleitor` VARCHAR(12) NULL,
  `zona` CHAR(3) NULL,
  `secao` CHAR(4) NULL,
  `numReservista` VARCHAR(13) NULL,
  `categoriaReservista` VARCHAR(15) NULL,
  PRIMARY KEY (`idIdentificacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ContatoInt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ContatoInt` (
  `idContato` INT NOT NULL AUTO_INCREMENT,
  `telefoneFixo` VARCHAR(15) NULL,
  `telefoneMovel` VARCHAR(16) NOT NULL,
  `emailPrim` VARCHAR(45) NOT NULL,
  `emailSec` VARCHAR(45) NULL,
  PRIMARY KEY (`idContato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ColaboradorTipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ColaboradorTipo` (
  `idColaboradorTipo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`idColaboradorTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Colaborador` (
  `idColaborador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(55) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `dtNasc` DATE NULL,
  `localNasc` VARCHAR(45) NULL,
  `estdCivil` CHAR(1) NULL,
  `etinia` VARCHAR(15) NULL,
  `nomeMae` VARCHAR(55) NULL,
  `nomePai` VARCHAR(55) NULL,
  `pais` VARCHAR(45) NULL,
  `endereco` VARCHAR(145) NULL,
  `complemento` VARCHAR(45) NULL,
  `resPropria` TINYINT NULL,
  `resFgts` TINYINT NULL,
  `Identificacao_idIdentificacao` INT NOT NULL,
  `escolaridade` CHAR(1) NULL,
  `ContatoInt_idContato` INT NOT NULL,
  `ColaboradorTipo_idColaboradorTipo` INT NOT NULL,
  `Funcao_idFuncao` INT NOT NULL,
  `defMotor` TINYINT NOT NULL,
  `defVisual` TINYINT NOT NULL,
  `defAuditiva` TINYINT NOT NULL,
  `obsDef` VARCHAR(150) NULL,
  `empresa` VARCHAR(45) NULL,
  `cnpj` VARCHAR(18) NULL,
  `obsEmpresa` VARCHAR(50) NULL,
  `remuneracaoEmpresa` DECIMAL NULL,
  `sigla` VARCHAR(6) NULL,
  PRIMARY KEY (`idColaborador`),
  INDEX `fk_Colaborador_Identificacao1_idx` (`Identificacao_idIdentificacao` ASC),
  INDEX `fk_Colaborador_ContatoInt1_idx` (`ContatoInt_idContato` ASC),
  INDEX `fk_Colaborador_ColaboradorTipo1_idx` (`ColaboradorTipo_idColaboradorTipo` ASC),
  INDEX `fk_Colaborador_Funcao1_idx` (`Funcao_idFuncao` ASC),
  CONSTRAINT `fk_Colaborador_Identificacao1`
    FOREIGN KEY (`Identificacao_idIdentificacao`)
    REFERENCES `mydb`.`Identificacao` (`idIdentificacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_ContatoInt1`
    FOREIGN KEY (`ContatoInt_idContato`)
    REFERENCES `mydb`.`ContatoInt` (`idContato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_ColaboradorTipo1`
    FOREIGN KEY (`ColaboradorTipo_idColaboradorTipo`)
    REFERENCES `mydb`.`ColaboradorTipo` (`idColaboradorTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Funcao1`
    FOREIGN KEY (`Funcao_idFuncao`)
    REFERENCES `mydb`.`Funcao` (`idFuncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ColaboradorExtr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ColaboradorExtr` (
  `idColaboradorExtr` INT NOT NULL AUTO_INCREMENT,
  `Colaborador_idColaborador` INT NOT NULL,
  `dtChegada` DATE NULL,
  `dtNaturalizacao` DATE NULL,
  `casadoBrasileiro` CHAR(1) NULL,
  `filhoBrasileiro` CHAR(1) NULL,
  PRIMARY KEY (`idColaboradorExtr`, `Colaborador_idColaborador`),
  INDEX `fk_ColaboradorExtr_Colaborador1_idx` (`Colaborador_idColaborador` ASC),
  CONSTRAINT `fk_ColaboradorExtr_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `mydb`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Banco` (
  `idBanco` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idBanco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoConta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoConta` (
  `idTipoConta` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoConta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InfoBanco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`InfoBanco` (
  `agencia` VARCHAR(10) NOT NULL,
  `numConta` VARCHAR(9) NOT NULL,
  `tipo` INT NOT NULL,
  `Banco_idBanco` INT NOT NULL,
  `Colaborador_idColaborador` INT NOT NULL,
  `TipoConta_idTipoConta` INT NOT NULL,
  `obs` VARCHAR(145) NULL,
  INDEX `fk_InfoBanco_Banco1_idx` (`Banco_idBanco` ASC),
  PRIMARY KEY (`Colaborador_idColaborador`),
  INDEX `fk_InfoBanco_TipoConta1_idx` (`TipoConta_idTipoConta` ASC),
  CONSTRAINT `fk_InfoBanco_Banco1`
    FOREIGN KEY (`Banco_idBanco`)
    REFERENCES `mydb`.`Banco` (`idBanco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InfoBanco_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `mydb`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_InfoBanco_TipoConta1`
    FOREIGN KEY (`TipoConta_idTipoConta`)
    REFERENCES `mydb`.`TipoConta` (`idTipoConta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dependente` (
  `idDependente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `dtNasc` DATE NOT NULL,
  `cpf` VARCHAR(14) NULL,
  `tipo` INT NOT NULL,
  `irrf` CHAR(1) NULL,
  `salarioFamilia` CHAR(1) NULL,
  `Colaborador_idColaborador` INT NOT NULL,
  PRIMARY KEY (`idDependente`),
  INDEX `fk_Dependente_Colaborador1_idx` (`Colaborador_idColaborador` ASC),
  CONSTRAINT `fk_Dependente_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `mydb`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DocumentoColaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DocumentoColaborador` (
  `cpf` LONGBLOB NULL,
  `tituloEleitor` LONGBLOB NULL,
  `tituloReservista` LONGBLOB NULL,
  `pisPasepInss` LONGBLOB NULL,
  `rg` LONGBLOB NULL,
  `certCasamento` LONGBLOB NULL,
  `compResidencia` LONGBLOB NULL,
  `compEscolar` LONGBLOB NULL,
  `cartaoBanco` LONGBLOB NULL,
  `rgCertidaoDependentes` LONGBLOB NULL,
  `carteiraVacinacaoFilhos` LONGBLOB NULL,
  `carteiraTrabalho` LONGBLOB NULL,
  `Colaborador_idColaborador` INT NOT NULL,
  PRIMARY KEY (`Colaborador_idColaborador`),
  CONSTRAINT `fk_DocumentoColaborador_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `mydb`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente_has_Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_has_Servico` (
  `Cliente_idCliente` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  `preco` DECIMAL NOT NULL,
  INDEX `fk_Cliente_has_Servico_Servico1_idx` (`Servico_idServico` ASC),
  INDEX `fk_Cliente_has_Servico_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Cliente_has_Servico_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Servico_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `mydb`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Feriado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Feriado` (
  `idFeriado` INT NOT NULL,
  `dia` DATE NOT NULL,
  `obs` VARCHAR(145) NULL,
  PRIMARY KEY (`idFeriado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto_has_Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_has_Fornecedor` (
  `Produto_idProduto` INT NOT NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`),
  INDEX `fk_Produto_has_Fornecedor_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC),
  INDEX `fk_Produto_has_Fornecedor_Produto1_idx` (`Produto_idProduto` ASC),
  CONSTRAINT `fk_Produto_has_Fornecedor_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Fornecedor_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servico_has_Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servico_has_Fornecedor` (
  `Servico_idServico` INT NOT NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`),
  INDEX `fk_Servico_has_Fornecedor_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC),
  INDEX `fk_Servico_has_Fornecedor_Servico1_idx` (`Servico_idServico` ASC),
  CONSTRAINT `fk_Servico_has_Fornecedor_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `mydb`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_has_Fornecedor_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OS` (
  `idOS` INT NOT NULL AUTO_INCREMENT,
  `dtPedido` DATE NOT NULL,
  `dtEntrega` DATE NULL,
  `horas` TIME NULL,
  `quantidade` INT NULL,
  `custoKm` DECIMAL NULL,
  `detalhamento` TEXT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Servico_idServico` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `horasExtras` INT NULL,
  `horasNoturnas` INT NULL,
  `Colaborador_idColaborador` INT NOT NULL,
  `prazoEntrega` DATE NULL,
  PRIMARY KEY (`idOS`),
  INDEX `fk_OS_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_OS_Servico1_idx` (`Servico_idServico` ASC),
  INDEX `fk_OS_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_OS_Colaborador1_idx` (`Colaborador_idColaborador` ASC),
  CONSTRAINT `fk_OS_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_Servico1`
    FOREIGN KEY (`Servico_idServico`)
    REFERENCES `mydb`.`Servico` (`idServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `mydb`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

/*
-- -----------------------------------------------------
-- Table `mydb`.`Contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contas` (
)
ENGINE = InnoDB;
*/

-- -----------------------------------------------------
-- Table `mydb`.`Equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipamento` (
  `idEquipamento` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(145) NULL,
  PRIMARY KEY (`idEquipamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcao_has_Equipamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcao_has_Equipamento` (
  `Funcao_idFuncao` INT NOT NULL,
  `Equipamento_idEquipamento` INT NOT NULL,
  INDEX `fk_Funcao_has_Equipamento_Equipamento1_idx` (`Equipamento_idEquipamento` ASC),
  INDEX `fk_Funcao_has_Equipamento_Funcao1_idx` (`Funcao_idFuncao` ASC),
  CONSTRAINT `fk_Funcao_has_Equipamento_Funcao1`
    FOREIGN KEY (`Funcao_idFuncao`)
    REFERENCES `mydb`.`Funcao` (`idFuncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcao_has_Equipamento_Equipamento1`
    FOREIGN KEY (`Equipamento_idEquipamento`)
    REFERENCES `mydb`.`Equipamento` (`idEquipamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EPI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EPI` (
  `idEpi` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(145) NULL,
  PRIMARY KEY (`idEpi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcao_has_EPI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcao_has_EPI` (
  `Funcao_idFuncao` INT NOT NULL,
  `EPI_idEpi` INT NOT NULL,
  PRIMARY KEY (`Funcao_idFuncao`, `EPI_idEpi`),
  INDEX `fk_Funcao_has_EPI_EPI1_idx` (`EPI_idEpi` ASC),
  INDEX `fk_Funcao_has_EPI_Funcao1_idx` (`Funcao_idFuncao` ASC),
  CONSTRAINT `fk_Funcao_has_EPI_Funcao1`
    FOREIGN KEY (`Funcao_idFuncao`)
    REFERENCES `mydb`.`Funcao` (`idFuncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcao_has_EPI_EPI1`
    FOREIGN KEY (`EPI_idEpi`)
    REFERENCES `mydb`.`EPI` (`idEpi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ocorrencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ocorrencias` (
  `idOcorrencias` INT NOT NULL,
  `dtOcorrencia` DATE NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idOcorrencias`),
  INDEX `fk_Ocorrencias_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Ocorrencias_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certificacao_has_Colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Certificacao_has_Colaborador` (
  `Certificacao_idCertificacao` INT NOT NULL,
  `Colaborador_idColaborador` INT NOT NULL,
  INDEX `fk_Certificacao_has_Colaborador_Colaborador1_idx` (`Colaborador_idColaborador` ASC),
  INDEX `fk_Certificacao_has_Colaborador_Certificacao1_idx` (`Certificacao_idCertificacao` ASC),
  CONSTRAINT `fk_Certificacao_has_Colaborador_Certificacao1`
    FOREIGN KEY (`Certificacao_idCertificacao`)
    REFERENCES `mydb`.`Certificacao` (`idCertificacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Certificacao_has_Colaborador_Colaborador1`
    FOREIGN KEY (`Colaborador_idColaborador`)
    REFERENCES `mydb`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Formulario` (
  `idFormulario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idFormulario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Campo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Campo` (
  `idFormulario` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NULL,
  `identCod` VARCHAR(45) NOT NULL,
  `Formulario_idFormulario` INT NOT NULL,
  PRIMARY KEY (`idFormulario`, `identCod`),
  INDEX `fk_Campo_Formulario1_idx` (`Formulario_idFormulario` ASC),
  CONSTRAINT `fk_Campo_Formulario1`
    FOREIGN KEY (`Formulario_idFormulario`)
    REFERENCES `mydb`.`Formulario` (`idFormulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Permicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Permicao` (
  `idPermicao` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idPermicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcao_has_Permicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcao_has_Permicao` (
  `Funcao_idFuncao` INT NOT NULL,
  `Permicao_idPermicao` INT NOT NULL,
  INDEX `fk_Funcao_has_Permicao_Permicao1_idx` (`Permicao_idPermicao` ASC),
  INDEX `fk_Funcao_has_Permicao_Funcao1_idx` (`Funcao_idFuncao` ASC),
  CONSTRAINT `fk_Funcao_has_Permicao_Funcao1`
    FOREIGN KEY (`Funcao_idFuncao`)
    REFERENCES `mydb`.`Funcao` (`idFuncao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcao_has_Permicao_Permicao1`
    FOREIGN KEY (`Permicao_idPermicao`)
    REFERENCES `mydb`.`Permicao` (`idPermicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
